### PR TITLE
Update to new marked version

### PR DESCRIPTION
**Pull request by zeckson**
https://github.com/firede/msee/issues/58

### CODE REVIEW

**Comment by elyalvarado** [comment]
I can confirm the issue exists, and is affecting workshopper-adventure and javascripting (as well as any other workshops) which is really frustrating for newbies trying to run them.

**Comment by UziTech** [comment]
Hold up on merging this PR. `marked` might revert the breaking change making this break again at the next release.

I would also suggest not pinning to a specific version otherwise you will be missing security patches.

**Comment by martinheidegger** [comment]
I agree with @UziTech - this should probably be fixed by marked. Closing this issue for now.

**Comment by zeckson** [comment]
What is the workaround guys?

**Pull request closed without merging**
