### PR TITLE
add support for tables.

### PR DESCRIPTION
**Pull request by lvivier**
I've added support for tables using [substack's text-table](https://github.com/substack/text-table).

Automatic widths, left/center/right alignment, and inline styles all work:

screen shot 2015-03-29 at 2 30 43 pm

### CODE REVIEW

**Comment by martinheidegger** [comment]
I had to fix a little to merge it into master but it seems to be added now.

**Comment by lvivier** [comment]
Woohoo!

**Comment by martinheidegger** [comment]
@firede Waiting for your publishing.

**Comment by firede** [comment]
@martinheidegger done.

**Comment by martinheidegger** [comment]
:+1:

**Pull request merged**
